In [1]:
import numpy as np
sample_list = [1,2,3]
list_array = np.array(sample_list)

In [2]:
print(list_array)

[1 2 3]


In [3]:
tup = (1,2,3)
my_tup_array = np.array(tup)

In [4]:
print(my_tup_array)

[1 2 3]


In [12]:
def multiply_loops(A, B):
    c=np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for k in range(B.shape[1]):
            c[i,k] = 0
            for j in range(B.shape[0]):
                n = A[i,j] * B[j,k]
                c[i,k] += n
    return c

In [13]:
def multiply_vector(A, B):
    return A @ B

In [16]:
X = np.random.random((100, 100))
Y = np.random.random((100, 100))

In [17]:
%time multiply_loops(X, Y)
%time multiply_vector(X, Y)

CPU times: user 607 ms, sys: 0 ns, total: 607 ms
Wall time: 603 ms
CPU times: user 8.54 ms, sys: 0 ns, total: 8.54 ms
Wall time: 8.97 ms


array([[22.86461156, 22.18808875, 21.8119742 , ..., 24.5141324 ,
        23.80800226, 20.79527277],
       [24.54284578, 25.41667058, 23.67341629, ..., 24.20462462,
        24.98325888, 21.96498994],
       [24.81588468, 24.39396333, 24.73951449, ..., 25.80928414,
        25.41441384, 22.77352333],
       ...,
       [25.71303595, 24.56637717, 23.12045544, ..., 24.30289848,
        24.47063608, 21.90030411],
       [26.49916067, 24.3375958 , 25.80857093, ..., 27.82570389,
        26.00942904, 21.89617153],
       [29.17080977, 28.0531301 , 28.64778875, ..., 28.99934345,
        28.30816142, 25.13982811]])

In [19]:
tup_dim = (3, 4)
samp_arr = np.array(tup_dim)
print(samp_arr)

[3 4]


In [59]:
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)
print(my_zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [25]:
my_ones_array = np.ones(tup_dim, dtype=np.int16)
print(my_ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [26]:
my_seven_array = np.full(tup_dim, 7, dtype=np.int16)
print(my_seven_array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [34]:
my_identity_array = np.identity(4, dtype=np.float64)
print(my_identity_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [87]:
my_rand_array = np.random.rand(3, 4)
print(my_rand_array)

[[0.1005565  0.66341861 0.08167119 0.48836377]
 [0.85609845 0.73833888 0.12650246 0.54794019]
 [0.66380584 0.28403863 0.68879486 0.10811113]]


In [94]:
tup_dim = (3, 4)
my_uninitialized_array = np.empty(tup_dim)
print(my_uninitialized_array)

[[0.1005565  0.66341861 0.08167119 0.48836377]
 [0.85609845 0.73833888 0.12650246 0.54794019]
 [0.66380584 0.28403863 0.68879486 0.10811113]]


In [106]:
my_range_array = np.arange(10, 30, 5)
print(my_range_array)

[10 15 20 25]


In [111]:
my_spaced_array = np.linspace(0, 5/3, 6)
print(my_spaced_array)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [1]:
import numpy as np
my_array = np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])

In [2]:
print(my_array)

[[ 1  4  5  6]
 [ 7  8  9 10]
 [11 12 14 16]]


In [13]:
my_array.ndim

2

In [14]:
my_array.shape

(3, 4)

In [15]:
my_array.dtype

dtype('int64')

In [16]:
my_array.size

12

In [2]:
import numpy as np
import os

In [3]:
import pandas as pd
# defining housing.csv file path
HOUSING_PATH = '../ml/machine_learning/datasets/housing/'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)

FileNotFoundError: [Errno 2] File b'../ml/machine_learning/datasets/housing/housing.csv' does not exist: b'../ml/machine_learning/datasets/housing/housing.csv'

In [ ]:
import numpy as np
name_arr, address_arr, zipcode_arr = np.loadtxt('my_file.txt', skiprows=2, unpack=True)

In [21]:
FILE = "housing_short.csv"

In [22]:
def load_housing_data(file = FILE ):
    return np.loadtxt(file, dtype={'names': ('longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households','median_income','median_house_value','ocean_proximity'),'formats': ('f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', 'f8', '|S15')}, delimiter=',', skiprows=1, unpack=True)

In [23]:
longitude_arr,latitude_arr,housing_median_age_arr,total_rooms_arr,total_bedrooms_arr,population_arr,households_arr,median_income_arr,median_house_value_arr,ocean_proximity_arr = load_housing_data()

In [24]:
print(median_house_value_arr)

[452600. 358500. 352100. 341300. 342200.]


In [4]:
import numpy as np
import os

In [7]:
import pandas as pd
# defining housing.csv file path
HOUSING_PATH = 'ml/machine_learning/datasets/housing/'
# reading the large housing.csv file using pandas
housing_raw = pd.read_csv(os.path.join(HOUSING_PATH, "housing.csv"))
# extracting only a few rows (5 rows) of data from the pandas dataframe 'my_df'
my_df = housing_raw.iloc[ : 5]
# creating a new small csv file - 'housing_short.csv' - containing the above extracted 5 rows of data
my_df.to_csv('housing_short.csv', index=False)